# audit_definitions.py
# Dictionary of UK audit terms and their definitions (memorable, light-hearted, accurate)

audit_definitions = {
    "Materiality": "Big enough to matter, small enough to ignore? Materiality is the difference!",
    "Substantive Testing": "Double-checking the numbers—like a maths test, but for grown-ups.",
    "ISA 315": "The standard for knowing your client. Auditors play detective!",
    "ISA 240": "The fraud-finder. Auditors look for sneaky business.",
    "ISA 330": "How to respond to risks. Umbrella ready if it rains!",
    "ISA 700": "The final report. Auditors give their verdict—thumbs up or down.",
    "ISA 520": "Analytical procedures—spot the odd one out!",
    "ISA 540": "Estimates and guesses. Auditors check if they’re sensible.",
    "ISA 570": "Going concern—will the business survive?",
    "ISA 580": "Management’s written promises. Pinky swear!",
    "ISA 600": "Group audits—herding cats across companies.",
    "ISA 610": "Using internal audit’s work. Teamwork makes the dream work!",
    "ISA 620": "Expert help—call a friend if you need one.",
    "Going Concern": "Will the business keep going, or is it time to pack up?",
    "Audit Risk": "Chance the auditor misses something. Look both ways!",
    "Control Environment": "The company’s honesty vibe. Good behaviour = good controls.",
    "Sampling": "Check a few, not all. Like taste-testing crisps.",
    "Engagement Letter": "The audit contract. No surprises!",
    "Audit Opinion": "Auditor’s verdict. Like a movie review.",
    "Assertions": "Management’s claims. Auditors check if they’re true.",
    "ICAEW Code of Ethics": "The moral compass. Keeps auditors honest.",
    "External Confirmation": "Proof from outside. Ask the bank!",
    "Analytical Procedures": "Spotting oddities. If it looks weird, dig deeper!",
    "Audit Evidence": "Proof for the audit. The more, the merrier.",
    "Audit Planning": "Map out the audit road trip.",
    "Risk Assessment": "Where could things go wrong?",
    "Test of Controls": "Do the safety nets work?",
    "Substantive Procedures": "Deep dives into the details.",
    "Audit Documentation": "The audit diary. Write it all down!",
    "Audit Trail": "Breadcrumbs from start to finish.",
    "Professional Skepticism": "Trust, but verify!",
    "Independence": "No strings attached. Auditors stay neutral.",
    "Ethical Standards": "Play fair, or you’re out!",
    "Audit Committee": "The company’s watchdog.",
    "Internal Audit": "In-house detective work.",
    "External Audit": "Independent check-up.",
    "Audit File": "Where all audit stuff lives.",
    "Audit Partner": "The boss of the audit team.",
    "Audit Manager": "Keeps the audit on track.",
    "Audit Senior": "Experienced auditor, not quite the boss.",
    "Audit Junior": "Newbie auditor, learning the ropes.",
    "Audit Findings": "What the audit discovered.",
    "Audit Recommendations": "Auditor’s helpful tips.",
    "Audit Follow-up": "Did they fix it? Check again!",
    "Audit Scope": "What’s included in the audit.",
    "Audit Methodology": "How the audit is done.",
    "Audit Standards": "The rules auditors follow.",
    "Audit Quality": "How good is the audit?",
    "Audit Review": "Double-checking the audit work.",
    "Audit Engagement": "The audit job itself.",
    "Audit Client": "Who’s being audited?",
    "Audit Fees": "What the audit costs.",
    "Audit Timetable": "Audit schedule—don’t be late!",
    "Audit Risks": "Things that could go wrong in the audit.",
    "Audit Controls": "Company’s safety nets.",
    "Audit Testing": "Checking if things work.",
    "Audit Completion": "All done! Time for the report.",
    "Audit Communication": "Talking with the client.",
    "Audit Working Papers": "Audit homework—keep it tidy.",
    "Audit Population": "All the items you could check.",
    "Audit Selection": "Which items to check?",
    "Audit Results": "What did the audit find?",
    "Audit Issues": "Problems found during the audit.",
    "Audit Adjustments": "Fixes made after the audit.",
    "Audit Observation": "What the auditor saw.",
    "Audit Inquiry": "Asking questions to learn more.",
    "Audit Confirmation": "Getting proof from others.",
    "Audit Inspection": "Looking at stuff up close.",
    "Audit Analysis": "Breaking things down to understand.",
    "Audit Techniques": "Audit tricks and tools.",
    "Audit Tools": "Handy things for the audit job.",
    "Audit Software": "Computer help for the audit.",
    "Audit Automation": "Let the robots do the boring bits.",
    "Audit Analytics": "Crunching numbers for clues.",
    "Audit Data": "All the info auditors use.",
    "Audit Reasoning": "Thinking it through logically.",
    "Audit Judgment": "Making smart audit decisions.",
    "Audit Professionalism": "Acting like a pro, always.",
    "Audit Ethics": "Doing the right thing.",
    "Audit Integrity": "Being honest, even when no one’s looking.",
    "Audit Objectivity": "No bias—just the facts!"
}
